
                                                                                                                                                                                                               /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Conexao.ConexaoBD;
import Dao.DaoRecipsonista;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import modelo.ModRecipsonista;
import modelo.ModeloTabela;

/**
 *
 * @author dota-
 */
public class FormCadRecipsonista extends javax.swing.JFrame {
int flag = 0;
ModRecipsonista mod = new ModRecipsonista();
DaoRecipsonista dao = new DaoRecipsonista();
ConexaoBD con = new ConexaoBD();
    /**
     * Creates new form FormCadRecipsonista
     */
    public FormCadRecipsonista() {
        initComponents();
        con.conexao();
        preecherTabela("select * from recipsonista order by r_nome");
        con.desconecta();
        
        try{
            MaskFormatter form = new MaskFormatter("(##)#####-####");
            jFormattedTextFieldCel.setFormatterFactory(new DefaultFormatterFactory(form));
            
        }catch (ParseException ex) {
            
        }
        
        try{
            MaskFormatter form = new MaskFormatter("(##)####-####");
            jFormattedTextFieldTel.setFormatterFactory(new DefaultFormatterFactory(form));
            
        }catch (ParseException ex) {
    }
    
         try{
            MaskFormatter form = new MaskFormatter("###.###.###-##");
            jTextFieldCpf.setFormatterFactory(new DefaultFormatterFactory(form));
            
        }catch (ParseException ex) {
            
        }
        
        try{
            MaskFormatter form = new MaskFormatter("##.###.###-#");
            jTextFieldRg.setFormatterFactory(new DefaultFormatterFactory(form));
            
        }catch (ParseException ex) {
    
    }}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelRua = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelRg = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelCPF = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jTextFieldEnd = new javax.swing.JTextField();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelNome1 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCel = new javax.swing.JFormattedTextField();
        jLabelBairro1 = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelBairro2 = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jLabelBairro3 = new javax.swing.JLabel();
        jDateChooserData = new com.toedter.calendar.JDateChooser();
        jFormattedTextFieldTel = new javax.swing.JFormattedTextField();
        jTextFieldRg = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Cadastro de Recipsonista");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 10, 190, 17);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelRua.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelRua.setText("Endereço");

        jLabelBairro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelBairro.setText("Bairro:");

        jTextFieldEmail.setEnabled(false);

        jLabelRg.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelRg.setText("RG:");

        jTextFieldNome.setEnabled(false);

        jLabelCPF.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelCPF.setText("CPF:");

        jLabelCelular.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelCelular.setText("Celular:");

        jTextFieldEnd.setEnabled(false);

        jLabelTelefone.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelTelefone.setText("Telefone:");

        jLabelNome.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelNome.setText("Nome:");

        jTextFieldBairro.setEnabled(false);

        jLabelNome1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelNome1.setText("Codigo:");

        jTextFieldCod.setEnabled(false);

        jLabelEmail.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelEmail.setText("E-mail:");

        jTextFieldCpf.setEnabled(false);

        jFormattedTextFieldCel.setEnabled(false);

        jLabelBairro1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelBairro1.setText("Cidade:");

        jTextFieldCidade.setEnabled(false);

        jLabelBairro2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelBairro2.setText("Estado:");

        jTextFieldEstado.setEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jLabelBairro3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelBairro3.setText("Data de Nascimento:");

        jDateChooserData.setEnabled(false);

        jFormattedTextFieldTel.setEnabled(false);

        jTextFieldRg.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBairro3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabelRua)
                .addGap(4, 4, 4)
                .addComponent(jTextFieldEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelNome1)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelNome)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCPF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelRg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelEmail)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCelular)
                        .addGap(4, 4, 4)
                        .addComponent(jFormattedTextFieldCel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelBairro)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelBairro2)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelBairro1)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jButtonNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelNome1))
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelCPF)
                                .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelRg)
                                .addComponent(jTextFieldRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelEmail))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFormattedTextFieldCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCelular))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTelefone))))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRua)
                            .addComponent(jDateChooserData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBairro3))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelBairro2)
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabelBairro))
                            .addComponent(jLabelBairro1))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 40, 780, 470);

        setSize(new java.awt.Dimension(815, 564));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
            jTextFieldCod.setText("");
            jTextFieldBairro.setText("");
            jTextFieldCidade.setText("");
            jTextFieldCpf.setText("");
            jTextFieldRg.setText("");
            jTextFieldEnd.setText("");
            jTextFieldNome.setText("");
            jTextFieldEstado.setText("");
            jFormattedTextFieldCel.setText("");
            jTextFieldCpf.setText("");
            jTextFieldEmail.setText("");
            jDateChooserData.setDate(null);
            jTextFieldNome.setEnabled(!true);
            jTextFieldCpf.setEnabled(!true);
            jTextFieldBairro.setEnabled(!true);
            jTextFieldCidade.setEnabled(!true);
            jTextFieldEmail.setEnabled(!true);
            jTextFieldEnd.setEnabled(!true);
            jTextFieldEstado.setEnabled(!true);
            jTextFieldRg.setEnabled(!true);
            jFormattedTextFieldCel.setEnabled(!true);
            jTextFieldCpf.setEnabled(!true);
            jButtonSalvar.setEnabled(!true);
            jButtonCancelar.setEnabled(!true);
            jDateChooserData.setEnabled(!true);
            jButtonExcluir.setEnabled(!true);
            jButtonEditar.setEnabled(!true);
            jFormattedTextFieldTel.setEnabled(!true);
            jButtonNovo.setEnabled(true);
            con.conexao();
            preecherTabela("select * from recipsonista order by r_nome");
            con.desconecta();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir!");
        if(resposta == JOptionPane.YES_OPTION){
           mod.setId( Integer.parseInt(jTextFieldCod.getText()));
           dao.Excluir(mod);
        }
        
            jTextFieldCod.setText("");
            jTextFieldBairro.setText("");
            jTextFieldCidade.setText("");
            jTextFieldCpf.setText("");
            jTextFieldRg.setText("");
            jTextFieldEnd.setText("");
            jTextFieldNome.setText("");
            jTextFieldEstado.setText("");
            jFormattedTextFieldCel.setText("");
            jTextFieldCpf.setText("");
            jTextFieldEmail.setText("");
            jDateChooserData.setDate(null);
            jTextFieldNome.setEnabled(!true);
            jTextFieldCpf.setEnabled(!true);
            jTextFieldBairro.setEnabled(!true);
            jTextFieldCidade.setEnabled(!true);
            jTextFieldEmail.setEnabled(!true);
            jTextFieldEnd.setEnabled(!true);
            jTextFieldEstado.setEnabled(!true);
            jTextFieldRg.setEnabled(!true);
            jFormattedTextFieldCel.setEnabled(!true);
            jTextFieldCpf.setEnabled(!true);
            jButtonSalvar.setEnabled(!true);
            jButtonCancelar.setEnabled(!true);
            jDateChooserData.setEnabled(!true);
            jButtonExcluir.setEnabled(!true);
            jButtonEditar.setEnabled(!true);
            jFormattedTextFieldTel.setEnabled(!true);
            jButtonNovo.setEnabled(true);
            con.conexao();
            preecherTabela("select * from recipsonista order by r_nome");
            con.desconecta();
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        if (flag==1){

            mod.setNome(jTextFieldNome.getText());
            mod.setCpf(jTextFieldCpf.getText());
            mod.setRg(jTextFieldRg.getText());
            mod.setDatasci(jDateChooserData.getDate());
            mod.setEstado(jTextFieldEstado.getText());
            mod.setEndereco(jTextFieldEnd.getText());
            mod.setCelular(jFormattedTextFieldCel.getText());
            mod.setTelefone(jFormattedTextFieldTel.getText());
            mod.setCidade(jTextFieldCidade.getText());
            mod.setBairro(jTextFieldBairro.getText());
            mod.setEmail(jTextFieldEmail.getText());
            dao.Salvar(mod);
            con.conexao();
            preecherTabela("select * from recipsonista order by r_nome");
            con.desconecta();

            jTextFieldCod.setText("");
            jTextFieldBairro.setText("");
            jTextFieldCidade.setText("");
            jTextFieldCpf.setText("");
            jTextFieldRg.setText("");
            jTextFieldEnd.setText("");
            jTextFieldNome.setText("");
            jTextFieldEstado.setText("");
            jFormattedTextFieldCel.setText("");
            jFormattedTextFieldTel.setText("");
            jTextFieldEmail.setText("");
            jDateChooserData.setDate(null);
            jTextFieldNome.setEnabled(!true);
            jTextFieldCpf.setEnabled(!true);
            jTextFieldBairro.setEnabled(!true);
            jTextFieldCidade.setEnabled(!true);
            jTextFieldEmail.setEnabled(!true);
            jTextFieldEnd.setEnabled(!true);
            jTextFieldEstado.setEnabled(!true);
            jTextFieldRg.setEnabled(!true);
            jFormattedTextFieldCel.setEnabled(!true);
            jTextFieldCpf.setEnabled(!true);
            jButtonSalvar.setEnabled(!true);
            jButtonCancelar.setEnabled(!true);
            jDateChooserData.setEnabled(!true);
            jFormattedTextFieldTel.setEnabled(!true);
            jButtonExcluir.setEnabled(!true);
            jButtonEditar.setEnabled(!true);
            jButtonNovo.setEnabled(true);
            
        }else{
            
            mod.setNome(jTextFieldNome.getText());
            mod.setCpf(jTextFieldCpf.getText());
            mod.setRg(jTextFieldRg.getText());
            mod.setDatasci(jDateChooserData.getDate());
            mod.setEstado(jTextFieldEstado.getText());
            mod.setEndereco(jTextFieldEnd.getText());
            mod.setCelular(jFormattedTextFieldCel.getText());
            mod.setTelefone(jFormattedTextFieldTel.getText());
            mod.setCidade(jTextFieldCidade.getText());
            mod.setBairro(jTextFieldBairro.getText());
            mod.setEmail(jTextFieldEmail.getText());
            dao.Editar(mod);
            con.conexao();
            preecherTabela("select * from recipsonista order by r_nome");
            con.desconecta();
            jTextFieldCod.setText("");
            jTextFieldBairro.setText("");
            jTextFieldCidade.setText("");
            jTextFieldCpf.setText("");
            jTextFieldRg.setText("");
            jTextFieldEnd.setText("");
            jTextFieldNome.setText("");
            jTextFieldEstado.setText("");
            jFormattedTextFieldCel.setText("");
            jFormattedTextFieldTel.setText("");
            jTextFieldEmail.setText("");
            jDateChooserData.setDate(null);
            jTextFieldNome.setEnabled(!true);
            jTextFieldCpf.setEnabled(!true);
            jTextFieldBairro.setEnabled(!true);
            jTextFieldCidade.setEnabled(!true);
            jTextFieldEmail.setEnabled(!true);
            jTextFieldEnd.setEnabled(!true);
            jTextFieldEstado.setEnabled(!true);
            jTextFieldRg.setEnabled(!true);
            jFormattedTextFieldCel.setEnabled(!true);
            jFormattedTextFieldTel.setEnabled(!true);
            jButtonSalvar.setEnabled(!true);
            jButtonCancelar.setEnabled(!true);
            jDateChooserData.setEnabled(!true);
            jFormattedTextFieldTel.setEnabled(!true);
            jButtonExcluir.setEnabled(!true);
            jButtonEditar.setEnabled(!true);
            jButtonNovo.setEnabled(true);
            
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        jButtonExcluir.setEnabled(!true);
        flag = 2;
        mod.setPesquisa(jTextFieldNome.getText());
        ModRecipsonista model = dao.buscaRecipsonista(mod);
        jTextFieldNome.setText(model.getNome());
        jTextFieldEnd.setText((model.getEndereco()));
        jFormattedTextFieldCel.setText((model.getCelular()));
        jTextFieldCpf.setText(model.getTelefone());
        jTextFieldCidade.setText((model.getCidade()));
        jTextFieldEstado.setText((model.getEstado()));
        jTextFieldBairro.setText((model.getBairro()));
        jTextFieldEmail.setText(model.getEmail());
        jTextFieldRg.setText((model.getRg()));
        jDateChooserData.setDate((model.getDatasci()));
        jTextFieldCpf.setText((model.getCpf()));       
       
                
        jTextFieldNome.setEnabled(true);
        jTextFieldCpf.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jTextFieldEnd.setEnabled(true);
        jTextFieldEstado.setEnabled(true);
        jTextFieldRg.setEnabled(true);
        jFormattedTextFieldCel.setEnabled(true);
        jFormattedTextFieldTel.setEnabled(true);
        jTextFieldCpf.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jDateChooserData.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
        
        
        
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        flag = 1;
        jTextFieldNome.setEnabled(true);
        jTextFieldCpf.setEnabled(true);
        jTextFieldBairro.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jTextFieldEmail.setEnabled(true);
        jTextFieldEnd.setEnabled(true);
        jTextFieldEstado.setEnabled(true);
        jTextFieldRg.setEnabled(true);
        jFormattedTextFieldCel.setEnabled(true);
        jTextFieldCpf.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jDateChooserData.setEnabled(true);
        jFormattedTextFieldTel.setEnabled(true);
                
        
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        String nome = "" + jTable1.getValueAt(jTable1.getSelectedRow(), 1);
        con.conexao();
        
        con.executaSQL("select * from recipsonista where r_nome='"+ nome+"'");
        try {
           con.rs.first();
            jTextFieldCod.setText(String.valueOf(con.rs.getInt("id_recipsonista")));
            jTextFieldNome.setText(con.rs.getString("R_nome"));
            jTextFieldEnd.setText(con.rs.getString("R_endereco"));
            jTextFieldBairro.setText(con.rs.getString("R_bairro"));
            jTextFieldCidade.setText(con.rs.getString("r_cidade"));
            jTextFieldEstado.setText(con.rs.getString("r_estado"));
            jFormattedTextFieldCel.setText(con.rs.getString("r_celular"));
            jFormattedTextFieldTel.setText(con.rs.getString("r_telefone"));
            jTextFieldCpf.setText(con.rs.getString("r_cpf"));
            jTextFieldRg.setText(con.rs.getString("r_rg"));
            jDateChooserData.setDate(con.rs.getDate("r_datanasci"));
            jTextFieldEmail.setText(con.rs.getString("r_email"));
            
            
            
            jButtonCancelar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jButtonEditar.setEnabled(true);
            jButtonNovo.setEnabled(!true);
            
        } catch (SQLException ex) {
            Logger.getLogger(PesqMedico.class.getName()).log(Level.SEVERE, null, ex);
                       
        }
        
        con.desconecta();
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void preecherTabela(String SQL){
    ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"ID","Nome","Endereço","Telefone",};
    con.executaSQL(SQL);
         try {
             con.rs.first();
             do{
                 dados.add(new Object[]{con.rs.getInt("id_recipsonista"),con.rs.getString("r_nome"),con.rs.getString("r_endereco"),con.rs.getString("r_telefone") });
                }while(con.rs.next());
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, " Erro ao Preencher a Tabela! " + ex);
         }
         
   ModeloTabela modelo = new ModeloTabela(dados, Colunas);
   jTable1.setModel (modelo);
   jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
   jTable1.getColumnModel().getColumn(0).setResizable(false);
   jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
   jTable1.getColumnModel().getColumn(1).setResizable(false);
   jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
   jTable1.getColumnModel().getColumn(2).setResizable(false);
   jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
   jTable1.getColumnModel().getColumn(3).setResizable(false);
   jTable1.getTableHeader().setReorderingAllowed(false);
   jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
   jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadRecipsonista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadRecipsonista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadRecipsonista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadRecipsonista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadRecipsonista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private com.toedter.calendar.JDateChooser jDateChooserData;
    private javax.swing.JFormattedTextField jFormattedTextFieldCel;
    private javax.swing.JFormattedTextField jFormattedTextFieldTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelBairro1;
    private javax.swing.JLabel jLabelBairro2;
    private javax.swing.JLabel jLabelBairro3;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JLabel jLabelRg;
    private javax.swing.JLabel jLabelRua;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JFormattedTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEnd;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JFormattedTextField jTextFieldRg;
    // End of variables declaration//GEN-END:variables
}
