/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Conexao.ConexaoBD;
import Dao.DaoUsuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModUsuario;
import modelo.ModeloTabela;

/**
 *
 * @author Jonathan
 */
public class FormUsuario extends javax.swing.JFrame {
     int flag = 0;
    ModUsuario mod = new ModUsuario();
    DaoUsuario dao = new DaoUsuario();
    ConexaoBD con = new ConexaoBD();

    /**
     * Creates new form FormUsuario
     */
    public FormUsuario() {
        initComponents();
        con.conexao();
        preecherTabela("select * from usuarios");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePsqUsuario = new javax.swing.JTable();
        jLabelSenha = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelNome3 = new javax.swing.JLabel();
        jLabelNomeTipo = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldSenha_Usuario = new javax.swing.JPasswordField();
        jPasswordFieldCon_Senha_Usuario = new javax.swing.JPasswordField();
        jComboBoxTipo = new javax.swing.JComboBox();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAltera = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonPsq = new javax.swing.JButton();
        jLabelUsuario1 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Cadastro de Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(286, 11, 118, 17);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTablePsqUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePsqUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePsqUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePsqUsuario);

        jLabelSenha.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelSenha.setText("Senha:");

        jLabelUsuario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelUsuario.setText("Usuario:");

        jLabelNome3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelNome3.setText("Confirma Senha:");

        jLabelNomeTipo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelNomeTipo.setText("Tipo:");

        jTextFieldUsuario.setEnabled(false);

        jPasswordFieldSenha_Usuario.setEnabled(false);

        jPasswordFieldCon_Senha_Usuario.setEnabled(false);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Recepcionista", " " }));
        jComboBoxTipo.setEnabled(false);
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAltera.setText("Altera");
        jButtonAltera.setEnabled(false);
        jButtonAltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlteraActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Exclúir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabelNome.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelNome.setText("Nome:");

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jButtonPsq.setText("Pesquisa");
        jButtonPsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPsqActionPerformed(evt);
            }
        });

        jLabelUsuario1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelUsuario1.setText("Cod:");

        jTextFieldCod.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNomeTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPsq))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldSenha_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabelNome3)
                        .addGap(4, 4, 4)
                        .addComponent(jPasswordFieldCon_Senha_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jButtonNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAltera)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir)))
                .addGap(58, 115, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelUsuario1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsuario1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelUsuario))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNomeTipo))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNome)
                        .addComponent(jButtonPsq)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordFieldSenha_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSenha))
                    .addComponent(jPasswordFieldCon_Senha_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelNome3)))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonAltera)
                    .addComponent(jButtonExcluir)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 39, 710, 370);

        setSize(new java.awt.Dimension(749, 460));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        flag = 1;
        jButtonPsq.setEnabled(false);
        jTextFieldNome.setEnabled(!true);
        jTextFieldUsuario.setEnabled(true);
        jPasswordFieldCon_Senha_Usuario.setEnabled(true);
        jPasswordFieldSenha_Usuario.setEnabled(true);
        jComboBoxTipo.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jTextFieldNome.setText("");
        jTextFieldUsuario.setText("");
        jPasswordFieldCon_Senha_Usuario.setText("");
        jPasswordFieldSenha_Usuario.setText("");
        jTextFieldNome.setEnabled(!true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
       
        // TODO add your handling code here:
       
       if (jTextFieldUsuario.getText() .isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Usuário para continuar");
            jTextFieldUsuario.requestFocus();
        }else if (jPasswordFieldSenha_Usuario.getText() .isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha a Senha para continuar");
            jPasswordFieldSenha_Usuario.requestFocus();
        }else if (jPasswordFieldCon_Senha_Usuario.getText() .isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Confirmar Senha para continuar");
            jPasswordFieldCon_Senha_Usuario.requestFocus();
        }else if(jPasswordFieldSenha_Usuario.getText().equals(jPasswordFieldCon_Senha_Usuario.getText()))  
                                               
                if (flag==1){
            
                mod.setNome(jTextFieldNome.getText());
                mod.setUsuario(jTextFieldUsuario.getText());
                mod.setTipo((String) jComboBoxTipo.getSelectedItem());
                mod.setSenha(jPasswordFieldSenha_Usuario.getText());
                dao.Salvar(mod);
                jTextFieldNome.setEnabled(true);
                jTextFieldUsuario.setEnabled(false);
                jPasswordFieldCon_Senha_Usuario.setEnabled(false);
                jPasswordFieldSenha_Usuario.setEnabled(false);
                jComboBoxTipo.setEnabled(false);
                jButtonSalvar.setEnabled(false);
                jButtonCancelar.setEnabled(false);
                jButtonAltera.setEnabled(false);
                jButtonExcluir.setEnabled(false);
                jButtonPsq.setEnabled(true);
                jTextFieldNome.setEnabled(true);
                jTextFieldNome.setText("");
                jTextFieldUsuario.setText("");
                jPasswordFieldCon_Senha_Usuario.setText("");
                jPasswordFieldSenha_Usuario.setText("");
        con.conexao();
        preecherTabela("select * from usuarios");
                con.desconecta();
                jTextFieldNome.setEnabled(true);
        }else{
                mod.setNome(jTextFieldNome.getText());
                mod.setUsuario(jTextFieldUsuario.getText());
                mod.setTipo((String) jComboBoxTipo.getSelectedItem());
                mod.setSenha(jPasswordFieldSenha_Usuario.getText());
                dao.Editar(mod);
                jTextFieldNome.setEnabled(true);
                jTextFieldUsuario.setEnabled(false);
                jPasswordFieldCon_Senha_Usuario.setEnabled(false);
                jPasswordFieldSenha_Usuario.setEnabled(false);
                jComboBoxTipo.setEnabled(false);
                jButtonSalvar.setEnabled(false);
                jButtonCancelar.setEnabled(false);
                jButtonAltera.setEnabled(false);
                jButtonExcluir.setEnabled(false);
                jButtonPsq.setEnabled(true);
                jTextFieldNome.setEnabled(true);
                jTextFieldNome.setText("");
                jTextFieldUsuario.setText("");
                jPasswordFieldCon_Senha_Usuario.setText("");
                jPasswordFieldSenha_Usuario.setText("");
                con.conexao();
                preecherTabela("select * from usuarios");
                con.desconecta();
                           
        }else{
            JOptionPane.showMessageDialog(rootPane, "A senhas não comrespondem");
       }
       jTextFieldNome.setEnabled(true);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        
        jTextFieldNome.setEnabled(true);
        jTextFieldUsuario.setEnabled(false);
        jPasswordFieldCon_Senha_Usuario.setEnabled(false);
        jPasswordFieldSenha_Usuario.setEnabled(false);
        jComboBoxTipo.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonAltera.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonPsq.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldNome.setText("");
        jTextFieldUsuario.setText("");
        jPasswordFieldCon_Senha_Usuario.setText("");
        jPasswordFieldSenha_Usuario.setText("");
        con.conexao();
        preecherTabela("select * from usuarios");
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonPsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPsqActionPerformed
        // TODO add your handling code here:
            
        mod.setPesquisa(jTextFieldNome.getText());
        ModUsuario model = dao.buscaUsuario(mod);
        jTextFieldUsuario.setText((model.getNome()));
        jPasswordFieldSenha_Usuario.setText(model.getSenha());
        jPasswordFieldCon_Senha_Usuario.setText(model.getSenha());
        
        jButtonExcluir.setEnabled(true);
        jButtonAltera.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
        con.conexao();
        preecherTabela("select * from usuarios where use_usuario like'%"+mod.getPesquisa()+"%'");
        
    }//GEN-LAST:event_jButtonPsqActionPerformed

    private void jButtonAlteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlteraActionPerformed
        // TODO add your handling code here:
        flag = 2;
        mod.setPesquisa(jTextFieldUsuario.getText());
        ModUsuario model = dao.buscaUsuario(mod);
        jTextFieldNome.setText(model.getNome());
        jTextFieldUsuario.setText((model.getUsuario()));
        jPasswordFieldSenha_Usuario.setText((model.getSenha()));
        jPasswordFieldCon_Senha_Usuario.setText(model.getSenha());
        jComboBoxTipo.setSelectedItem(model.getTipo());
        jButtonPsq.setEnabled(false);
        jTextFieldNome.setEnabled(!true);
        jTextFieldUsuario.setEnabled(true);
        jPasswordFieldCon_Senha_Usuario.setEnabled(true);
        jPasswordFieldSenha_Usuario.setEnabled(true);
        jComboBoxTipo.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonAlteraActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        // TODO add your handling code here:
        
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir!");
        if(resposta == JOptionPane.YES_OPTION){
           mod.setCod(Integer.parseInt(jTextFieldCod.getText()));
           dao.Excluir(mod);
        }
        jTextFieldNome.setEnabled(true);
        jTextFieldUsuario.setEnabled(false);
        jPasswordFieldCon_Senha_Usuario.setEnabled(false);
        jPasswordFieldSenha_Usuario.setEnabled(false);
        jComboBoxTipo.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        jButtonAltera.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonPsq.setEnabled(true);
        jTextFieldNome.setText("");
        jTextFieldUsuario.setText("");
        jPasswordFieldCon_Senha_Usuario.setText("");
        jPasswordFieldSenha_Usuario.setText("");
        con.conexao();
        preecherTabela("select * from usuarios");
        con.desconecta();
        
        
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTablePsqUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePsqUsuarioMouseClicked
        // TODO add your handling code here:
        
        String nome = "" + jTablePsqUsuario.getValueAt(jTablePsqUsuario.getSelectedRow(), 1);
        con.conexao();
        
        con.executaSQL("select * from usuarios where use_usuario='"+ nome+"'");
        try {
            con.rs.first();
            jTextFieldCod.setText(String.valueOf(con.rs.getInt("use_cod")));
            jTextFieldUsuario.setText(con.rs.getString("use_usuario"));
            jPasswordFieldCon_Senha_Usuario.setText(con.rs.getString("use_senha"));
            jPasswordFieldSenha_Usuario.setText(con.rs.getString("use_senha"));
            jComboBoxTipo.setSelectedItem(con.rs.getString("use_tipo"));
            jButtonAltera.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jButtonCancelar.setEnabled(true);
            jButtonPsq.setEnabled(true);
            jTextFieldNome.setEnabled(true);
            jTextFieldUsuario.setEnabled(false);
            jPasswordFieldCon_Senha_Usuario.setEnabled(false);
            jPasswordFieldSenha_Usuario.setEnabled(false);
            jComboBoxTipo.setEnabled(false);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(PesqMedico.class.getName()).log(Level.SEVERE, null, ex);
                       
        }
        
        con.desconecta();
        
    }//GEN-LAST:event_jTablePsqUsuarioMouseClicked

    private void preecherTabela(String SQL){
    ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"ID","Usuario","Tipo",};
    con.executaSQL(SQL);
         try {
             con.rs.first();
             do{
                 dados.add(new Object[]{con.rs.getInt("use_cod"),con.rs.getString("use_usuario"),con.rs.getString("use_tipo") });
                }while(con.rs.next());
         } catch (SQLException ex) {
             }
         
   ModeloTabela modelo = new ModeloTabela(dados, Colunas);
   jTablePsqUsuario.setModel (modelo);
   jTablePsqUsuario.getColumnModel().getColumn(0).setPreferredWidth(50);
   jTablePsqUsuario.getColumnModel().getColumn(0).setResizable(false);
   jTablePsqUsuario.getColumnModel().getColumn(1).setPreferredWidth(250);
   jTablePsqUsuario.getColumnModel().getColumn(1).setResizable(false);
   jTablePsqUsuario.getColumnModel().getColumn(2).setPreferredWidth(166);
   jTablePsqUsuario.getColumnModel().getColumn(2).setResizable(false);
   jTablePsqUsuario.getTableHeader().setReorderingAllowed(false);
   jTablePsqUsuario.setAutoResizeMode(jTablePsqUsuario.AUTO_RESIZE_OFF);
   jTablePsqUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAltera;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPsq;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNome3;
    private javax.swing.JLabel jLabelNomeTipo;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelUsuario1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldCon_Senha_Usuario;
    private javax.swing.JPasswordField jPasswordFieldSenha_Usuario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePsqUsuario;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
