/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author dota-
 */
public class FormConsulta extends javax.swing.JFrame {

    /**
     * Creates new form FormConsulta
     */
    public FormConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanelCirugia = new javax.swing.JPanel();
        jLabelCod = new javax.swing.JLabel();
        jLabelObs = new javax.swing.JLabel();
        jLabelVacinaTomada = new javax.swing.JLabel();
        jLabelCirugia = new javax.swing.JLabel();
        jLabelDoençasDiagnosticadas = new javax.swing.JLabel();
        jLabelExamesRealizados = new javax.swing.JLabel();
        jLabelPeso = new javax.swing.JLabel();
        jLabelRaca = new javax.swing.JLabel();
        jLabelNomePaciente = new javax.swing.JLabel();
        jLabelNomeDono = new javax.swing.JLabel();
        jTextFieldCodFicha = new javax.swing.JTextField();
        jTextFieldPaciente = new javax.swing.JTextField();
        jTextFieldDoencaDiagnosticada = new javax.swing.JTextField();
        jTextFieldPeso = new javax.swing.JTextField();
        jTextFieldRaça = new javax.swing.JTextField();
        jTextFieldNomedoDono = new javax.swing.JTextField();
        jTextFieldObsVeterinario = new javax.swing.JTextField();
        jTextFieldCirugiasRealizadas = new javax.swing.JTextField();
        jTextFieldExamesRealizados = new javax.swing.JTextField();
        jComboBoxVacinasTomadas = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabelTitulo.setText("Ficha Medica");
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(380, 10, 100, 17);

        jPanelCirugia.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelCod.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelCod.setText("Codigo:");

        jLabelObs.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelObs.setText("Obs. do Veterinario:");

        jLabelVacinaTomada.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelVacinaTomada.setText("Vacinas tomadas:");

        jLabelCirugia.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelCirugia.setText("Cirugias Realizadas:");

        jLabelDoençasDiagnosticadas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelDoençasDiagnosticadas.setText("Doenças Diagnosticadas:");

        jLabelExamesRealizados.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelExamesRealizados.setText("Exames Realizados:");

        jLabelPeso.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelPeso.setText("Peso:");

        jLabelRaca.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelRaca.setText("Raça:");

        jLabelNomePaciente.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelNomePaciente.setText("Nome do Paciente:");

        jLabelNomeDono.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelNomeDono.setText("Nome do Dono:");

        jComboBoxVacinasTomadas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelCirugiaLayout = new javax.swing.GroupLayout(jPanelCirugia);
        jPanelCirugia.setLayout(jPanelCirugiaLayout);
        jPanelCirugiaLayout.setHorizontalGroup(
            jPanelCirugiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCirugiaLayout.createSequentialGroup()
                .addComponent(jLabelCod, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCodFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelCirugiaLayout.createSequentialGroup()
                .addComponent(jLabelNomeDono, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomedoDono, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldPaciente)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCirugiaLayout.createSequentialGroup()
                .addGroup(jPanelCirugiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCirugiaLayout.createSequentialGroup()
                        .addComponent(jLabelObs, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldObsVeterinario))
                    .addGroup(jPanelCirugiaLayout.createSequentialGroup()
                        .addGroup(jPanelCirugiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCirugiaLayout.createSequentialGroup()
                                .addComponent(jLabelCirugia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldCirugiasRealizadas))
                            .addGroup(jPanelCirugiaLayout.createSequentialGroup()
                                .addComponent(jLabelRaca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldRaça, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelCirugiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCirugiaLayout.createSequentialGroup()
                                .addComponent(jLabelExamesRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldExamesRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelCirugiaLayout.createSequentialGroup()
                                .addComponent(jLabelDoençasDiagnosticadas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDoencaDiagnosticada, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCirugiaLayout.createSequentialGroup()
                        .addComponent(jLabelVacinaTomada, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxVacinasTomadas, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        jPanelCirugiaLayout.setVerticalGroup(
            jPanelCirugiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCirugiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCirugiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCod)
                    .addComponent(jTextFieldCodFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCirugiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeDono)
                    .addComponent(jTextFieldNomedoDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomePaciente)
                    .addComponent(jTextFieldPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanelCirugiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRaca)
                    .addComponent(jTextFieldRaça, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPeso)
                    .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelExamesRealizados)
                    .addComponent(jTextFieldExamesRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCirugiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCirugia)
                    .addComponent(jTextFieldCirugiasRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDoençasDiagnosticadas)
                    .addComponent(jTextFieldDoencaDiagnosticada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCirugiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVacinaTomada)
                    .addComponent(jComboBoxVacinasTomadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanelCirugiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelObs)
                    .addComponent(jTextFieldObsVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(297, 297, 297))
        );

        getContentPane().add(jPanelCirugia);
        jPanelCirugia.setBounds(10, 28, 824, 440);

        setSize(new java.awt.Dimension(860, 556));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxVacinasTomadas;
    private javax.swing.JLabel jLabelCirugia;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelDoençasDiagnosticadas;
    private javax.swing.JLabel jLabelExamesRealizados;
    private javax.swing.JLabel jLabelNomeDono;
    private javax.swing.JLabel jLabelNomePaciente;
    private javax.swing.JLabel jLabelObs;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabelRaca;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelVacinaTomada;
    private javax.swing.JPanel jPanelCirugia;
    private javax.swing.JTextField jTextFieldCirugiasRealizadas;
    private javax.swing.JTextField jTextFieldCodFicha;
    private javax.swing.JTextField jTextFieldDoencaDiagnosticada;
    private javax.swing.JTextField jTextFieldExamesRealizados;
    private javax.swing.JTextField jTextFieldNomedoDono;
    private javax.swing.JTextField jTextFieldObsVeterinario;
    private javax.swing.JTextField jTextFieldPaciente;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JTextField jTextFieldRaça;
    // End of variables declaration//GEN-END:variables
}
