/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloTabela;
import Conexao.ConexaoBD;
import Dao.DaoAgenda;
import modelo.ModAgenda;

/**
 *
 * @author dota-
 */
public class FormAgendamento extends javax.swing.JFrame {

    ConexaoBD con = new ConexaoBD();
    ModAgenda mod = new ModAgenda();
    DaoAgenda dao = new DaoAgenda();
    /**
     * Creates new form FormAgendamento
     */
    public FormAgendamento() {
        initComponents();
        preencherVeterinario();
      jTextFieldMotivo.setEnabled(false);
      jButtonRealizarAgendamento.setEnabled(false);
      jComboBoxTurno.setEnabled(false);
      jComboBoxVeterinario.setEditable(false);
      jDateChooserData.setEnabled(false);
      jButtonCancelarAgendamento.setEnabled(false);
      jDateChooserData.setDate(null);
      jTextFieldMotivo.setText("");
      jTextFieldPaciente.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelPaciente = new javax.swing.JLabel();
        jLabelTurno = new javax.swing.JLabel();
        jLabelPsqNome2 = new javax.swing.JLabel();
        jLabelPsqNome3 = new javax.swing.JLabel();
        jLabelPsqNome4 = new javax.swing.JLabel();
        jDateChooserData = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBoxTurno = new javax.swing.JComboBox();
        jComboBoxVeterinario = new javax.swing.JComboBox();
        jTextFieldMotivo = new javax.swing.JTextField();
        jButtonRealizarAgendamento = new javax.swing.JButton();
        jButtonCancelarAgendamento = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldPaciente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Agendamento");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 10, 90, 17);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelPaciente.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelPaciente.setText("Paciente:");

        jLabelTurno.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelTurno.setText("Turno:");

        jLabelPsqNome2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelPsqNome2.setText("Veterinario:");

        jLabelPsqNome3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelPsqNome3.setText("Motivo:");

        jLabelPsqNome4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelPsqNome4.setText("Data:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBoxTurno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matutino", "Vespertino" }));
        jComboBoxTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTurnoActionPerformed(evt);
            }
        });

        jComboBoxVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVeterinarioActionPerformed(evt);
            }
        });

        jButtonRealizarAgendamento.setText("Realizar Agendamento");
        jButtonRealizarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarAgendamentoActionPerformed(evt);
            }
        });

        jButtonCancelarAgendamento.setText("Cancelar Agendamento");
        jButtonCancelarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarAgendamentoActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPsqNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPsqNome4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserData, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelPsqNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonRealizarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCancelarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonBuscar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPaciente)
                    .addComponent(jLabelTurno)
                    .addComponent(jComboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jTextFieldPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPsqNome4)
                    .addComponent(jDateChooserData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPsqNome2)
                        .addComponent(jComboBoxVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPsqNome3)
                    .addComponent(jTextFieldMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRealizarAgendamento)
                    .addComponent(jButtonCancelarAgendamento))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 35, 598, 410);

        setSize(new java.awt.Dimension(634, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTurnoActionPerformed

    private void jComboBoxVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVeterinarioActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jComboBoxVeterinarioActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        String nomeanimal = "" + jTable1.getValueAt(jTable1.getSelectedRow(), 3);
        con.conexao();
        
        con.executaSQL("select * from animal where nome_animal='"+ nomeanimal+"'");
        try {
            con.rs.first();
            jTextFieldPaciente.setText(con.rs.getString("nome_animal"));
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao leva dados");
                       
        }
        
        con.desconecta();
        
      jTextFieldMotivo.setEnabled(true);
      jButtonRealizarAgendamento.setEnabled(true);
      jComboBoxTurno.setEnabled(true);
      jComboBoxVeterinario.setEditable(true);
      jDateChooserData.setEnabled(true);
      jButtonCancelarAgendamento.setEnabled(!false);
       
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        con.conexao();
        preecherTabela("select nome_proprietario, telefone, cpf, nome_animal from cliente inner join animal on cliente.cod_proprietario = animal.cod_proprietario where nome_animal like'%"+jTextFieldPaciente.getText()+"%'");
        con.desconecta();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonRealizarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarAgendamentoActionPerformed
        // TODO add your handling code here:
        mod.setNomePaciente(jTextFieldPaciente.getText());
        mod.setNomeVeterinario((String) jComboBoxVeterinario.getSelectedItem());
        mod.setMotivo(jTextFieldMotivo.getText());
        mod.setTurno((String) jComboBoxTurno.getSelectedItem());
        mod.setData(jDateChooserData.getDate());
        mod.setStatus("Aberto");
        dao.Salvar(mod);
        
        
        
        
        
    }//GEN-LAST:event_jButtonRealizarAgendamentoActionPerformed

    private void jButtonCancelarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarAgendamentoActionPerformed
        // TODO add your handling code here:
        jDateChooserData.setDate(null);
        jTextFieldMotivo.setText("");
        jTextFieldPaciente.setText("");
        jTextFieldMotivo.setEnabled(false);
        jButtonRealizarAgendamento.setEnabled(false);
        jComboBoxTurno.setEnabled(false);
        jComboBoxVeterinario.setEditable(false);
        jDateChooserData.setEnabled(false);
        jButtonCancelarAgendamento.setEnabled(false);
        
    }//GEN-LAST:event_jButtonCancelarAgendamentoActionPerformed

    public void preencherVeterinario(){
      con.conexao();
      con.executaSQL("select * from medicos order by nome");
      try{
          con.rs.first();
          jComboBoxVeterinario.removeAllItems();
          do{
              jComboBoxVeterinario.addItem(con.rs.getString("nome"));
            }while(con.rs.next());
          
      } catch (SQLException ex) {
          JOptionPane.showMessageDialog(rootPane,"Nenhum Veterinario Cadastrado");
      }
      con.desconecta();
    }
    
    
    private void preecherTabela(String SQL){
    ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"Nome","Telefone","CPF","Nome do Animal",};
    con.executaSQL(SQL);
         try {
             con.rs.first();
             do{
                 dados.add(new Object[]{con.rs.getString("nome_proprietario"),con.rs.getString("telefone"),con.rs.getString("cpf"),con.rs.getString("nome_animal") });
                }while(con.rs.next());
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, " Paciente Não Cadastrado! ");
         }
         
   ModeloTabela modelo = new ModeloTabela(dados, Colunas);
   jTable1.setModel (modelo);
   jTable1.getColumnModel().getColumn(0).setPreferredWidth(150);
   jTable1.getColumnModel().getColumn(0).setResizable(false);
   jTable1.getColumnModel().getColumn(1).setPreferredWidth(80);
   jTable1.getColumnModel().getColumn(1).setResizable(false);
   jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
   jTable1.getColumnModel().getColumn(2).setResizable(false);
   jTable1.getColumnModel().getColumn(3).setPreferredWidth(150);
   jTable1.getColumnModel().getColumn(3).setResizable(false);
   jTable1.getTableHeader().setReorderingAllowed(false);
   jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
   jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAgendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelarAgendamento;
    private javax.swing.JButton jButtonRealizarAgendamento;
    private javax.swing.JComboBox jComboBoxTurno;
    private javax.swing.JComboBox jComboBoxVeterinario;
    private com.toedter.calendar.JDateChooser jDateChooserData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPaciente;
    private javax.swing.JLabel jLabelPsqNome2;
    private javax.swing.JLabel jLabelPsqNome3;
    private javax.swing.JLabel jLabelPsqNome4;
    private javax.swing.JLabel jLabelTurno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldMotivo;
    private javax.swing.JTextField jTextFieldPaciente;
    // End of variables declaration//GEN-END:variables
}
