/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Conexao.ConexaoBD;
import Dao.DaoAgenda;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloTabela;

/**
 *
 * @author dota-
 */
public class FormeAgendaVeterinario extends javax.swing.JFrame {
ConexaoBD con = new ConexaoBD();
DaoAgenda dao = new DaoAgenda();
String dtHoje;
String status;
    /**
     * Creates new form FormeAgendaVeterinario
     */
    public FormeAgendaVeterinario() {
        initComponents();
        preencherVeterinario();
        Calendar data = Calendar.getInstance();
        Date d = data.getTime();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
              
        dtHoje = dateFormat.format(d);
        status = "Atendimento";
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelVeterinario = new javax.swing.JLabel();
        jComboBoxVeterinario = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabelPaciente = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabelTitulo.setText("Agenda do Veterinario");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabelVeterinario.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelVeterinario.setText("Veterinario:");

        jComboBoxVeterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVeterinarioActionPerformed(evt);
            }
        });

        jButton1.setText("Atender Agendamento");

        jLabelPaciente.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelPaciente.setText("Agenda de Paciente:");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(348, 348, 348))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVeterinario)
                    .addComponent(jComboBoxVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabelPaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(890, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxVeterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVeterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxVeterinarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int cod = dao.BuscaCodVeterinario((String) jComboBoxVeterinario.getSelectedItem());
        String codigo = String.valueOf(cod);
        con.conexao();
        preecherTabela("select * from agenda inner join animal on agenda.agenda_codpaciente = animal.cod_animal inner join medicos on agenda.agenda_codmedico = medicos.id_medico inner join cliente on cliente.cod_proprietario = animal.cod_proprietario where agenda_codmedico='"+cod+"' and agenda_data='"+dtHoje+"' and agenda_status = '"+status+"'");
        con.desconecta();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void preencherVeterinario(){
      con.conexao();
      con.executaSQL("select * from medicos order by nome");
      try{
          con.rs.first();
          jComboBoxVeterinario.removeAllItems();
          do{
              jComboBoxVeterinario.addItem(con.rs.getString("nome"));
            }while(con.rs.next());
          
      } catch (SQLException ex) {
          JOptionPane.showMessageDialog(rootPane,"Nenhum Veterinario Cadastrado");
      }
      con.desconecta();
    }
    
    private void preecherTabela(String SQL){
    ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"ID","Nome","Turno","Data","Status","Veterinario","Nome do Dono","Telefone",};
    con.executaSQL(SQL);
         try {
             con.rs.first();
             do{
                 dados.add(new Object[]{con.rs.getInt("id_agenda"),con.rs.getString("nome_animal"),con.rs.getString("agenda_turno"),con.rs.getString("agenda_data"),con.rs.getString("agenda_status"),con.rs.getString("nome"),con.rs.getString("nome_proprietario"),con.rs.getString("telefone") });
                }while(con.rs.next());
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, " Não tem nenhum atendimento agendado para este veterinario! ");
         }
         
   ModeloTabela modelo = new ModeloTabela(dados, Colunas);
   jTable1.setModel (modelo);
   jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
   jTable1.getColumnModel().getColumn(0).setResizable(false);
   jTable1.getColumnModel().getColumn(1).setPreferredWidth(220);
   jTable1.getColumnModel().getColumn(1).setResizable(false);
   jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
   jTable1.getColumnModel().getColumn(2).setResizable(false);
   jTable1.getColumnModel().getColumn(3).setPreferredWidth(80);
   jTable1.getColumnModel().getColumn(3).setResizable(false);
   jTable1.getColumnModel().getColumn(4).setPreferredWidth(120);
   jTable1.getColumnModel().getColumn(4).setResizable(false);
   jTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
   jTable1.getColumnModel().getColumn(5).setResizable(false);
   jTable1.getColumnModel().getColumn(6).setPreferredWidth(220);
   jTable1.getColumnModel().getColumn(6).setResizable(false);
   jTable1.getColumnModel().getColumn(7).setPreferredWidth(80);
   jTable1.getColumnModel().getColumn(7).setResizable(false);
   jTable1.getTableHeader().setReorderingAllowed(false);
   jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
   jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormeAgendaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormeAgendaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormeAgendaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormeAgendaVeterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormeAgendaVeterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBoxVeterinario;
    private javax.swing.JLabel jLabelPaciente;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelVeterinario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
