/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.ModeloTabela;
import Conexao.ConexaoBD;
import javax.swing.ListSelectionModel;
import modelo.ModMedico;
import Dao.DaoMedico;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Jonathan
 */
public class PesqMedico extends javax.swing.JFrame {

    ConexaoBD Connection = new ConexaoBD();
    FormMedico form = new FormMedico();
    DaoMedico control = new DaoMedico();
    ModMedico mod = new ModMedico();
    /**
     * Creates new form PesqMedico
     */
    public PesqMedico() {
        initComponents();
        Connection.conexao();
        preecherTabela("select * from medicos order by nome");
        jButtonCadMedicoExcluir.setEnabled(false);
        jButtonjButtonCadMedicoEditar.setEnabled(false);
        jButtonCadMedicoCancelar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePsqMedico = new javax.swing.JTable();
        jButtonCadMedicoNovo = new javax.swing.JButton();
        jButtonjButtonCadMedicoEditar = new javax.swing.JButton();
        jButtonCadMedicoExcluir = new javax.swing.JButton();
        jButtonCadMedicoCancelar = new javax.swing.JButton();
        jLabelPsqNome = new javax.swing.JLabel();
        jTextFieldNomePsq = new javax.swing.JTextField();
        jButtonCadMedicoPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Cadastro de Medicos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 10, 119, 17);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTablePsqMedico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTablePsqMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePsqMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePsqMedicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePsqMedico);

        jButtonCadMedicoNovo.setText("Novo");
        jButtonCadMedicoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadMedicoNovoActionPerformed(evt);
            }
        });

        jButtonjButtonCadMedicoEditar.setText("Altera");
        jButtonjButtonCadMedicoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonjButtonCadMedicoEditarActionPerformed(evt);
            }
        });

        jButtonCadMedicoExcluir.setText("Excluir");
        jButtonCadMedicoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadMedicoExcluirActionPerformed(evt);
            }
        });

        jButtonCadMedicoCancelar.setText("Cancelar");
        jButtonCadMedicoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadMedicoCancelarActionPerformed(evt);
            }
        });

        jLabelPsqNome.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelPsqNome.setText("Nome:");

        jTextFieldNomePsq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomePsqActionPerformed(evt);
            }
        });

        jButtonCadMedicoPesquisar.setText("Pesquisar");
        jButtonCadMedicoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadMedicoPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelPsqNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomePsq, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCadMedicoPesquisar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButtonCadMedicoNovo)
                        .addGap(31, 31, 31)
                        .addComponent(jButtonjButtonCadMedicoEditar)
                        .addGap(31, 31, 31)
                        .addComponent(jButtonCadMedicoExcluir)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonCadMedicoCancelar)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPsqNome)
                    .addComponent(jTextFieldNomePsq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadMedicoPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadMedicoNovo)
                    .addComponent(jButtonjButtonCadMedicoEditar)
                    .addComponent(jButtonCadMedicoExcluir)
                    .addComponent(jButtonCadMedicoCancelar))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 38, 720, 345);

        setSize(new java.awt.Dimension(820, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomePsqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomePsqActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldNomePsqActionPerformed

    private void jButtonCadMedicoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadMedicoNovoActionPerformed
        // TODO add your handling code here:
        form.flag = 1;
        form.setVisible(true);
        form.getjTextFieldCod().setText("");
        form.getjTextFieldCRM().setText("");
        form.getjTextFieldNome().setText("");
        dispose();
            
        
    }//GEN-LAST:event_jButtonCadMedicoNovoActionPerformed

    private void jButtonCadMedicoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadMedicoPesquisarActionPerformed
        Connection.conexao();    
        mod.setPesquisa(jTextFieldNomePsq.getText());
        ModMedico model = control.buscaMedico(mod);
        jTextFieldNomePsq.setText(model.getNome());
        form.getjTextFieldCod().setText(String.valueOf(model.getCodigo()));
        
        jButtonCadMedicoExcluir.setEnabled(true);
        jButtonjButtonCadMedicoEditar.setEnabled(true);
        jButtonCadMedicoCancelar.setEnabled(true);
        
        preecherTabela("select * from medicos where nome like'%"+mod.getPesquisa()+"%'");
    }//GEN-LAST:event_jButtonCadMedicoPesquisarActionPerformed

    private void jButtonjButtonCadMedicoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonjButtonCadMedicoEditarActionPerformed
        // TODO add your handling code here:
        Connection.conexao();
        form.flag = 2;
        form.setVisible(true);
        mod.setPesquisa(getjTextFieldNomePsq().getText());
        ModMedico model = control.buscaMedico(mod);
        form.getjTextFieldNome().setText(model.getNome());
        form.getjTextFieldCRM().setText(String.valueOf(model.getCrmv()));
        form.getjTextFieldCod().setText(String.valueOf(model.getCodigo()));
        form.getjComboBox1().setSelectedItem(model.getEspecialidade());
        dispose();
       
              
        
    }//GEN-LAST:event_jButtonjButtonCadMedicoEditarActionPerformed

    private void jButtonCadMedicoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadMedicoCancelarActionPerformed
        // TODO add your handling code here:
        getjTextFieldNomePsq().setText("");
        jButtonCadMedicoExcluir.setEnabled(false);
        jButtonjButtonCadMedicoEditar.setEnabled(false);
        jButtonCadMedicoCancelar.setEnabled(false);
    }//GEN-LAST:event_jButtonCadMedicoCancelarActionPerformed

    private void jButtonCadMedicoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadMedicoExcluirActionPerformed
        // TODO add your handling code here:
        
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir!");
        if(resposta == JOptionPane.YES_OPTION){
           mod.setCodigo(Integer.parseInt(form.getjTextFieldCod().getText()));
           control.Excluir(mod);
        }
        getjTextFieldNomePsq().setText("");
        
        jButtonCadMedicoExcluir.setEnabled(false);
        jButtonjButtonCadMedicoEditar.setEnabled(false);
        jButtonCadMedicoCancelar.setEnabled(false);
        Connection.conexao();
        preecherTabela("select * from medicos order by nome");
    }//GEN-LAST:event_jButtonCadMedicoExcluirActionPerformed

    private void jTablePsqMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePsqMedicoMouseClicked
        // TODO add your handling code here:
        String nome = "" + jTablePsqMedico.getValueAt(jTablePsqMedico.getSelectedRow(), 1);
        Connection.conexao();
        
        Connection.executaSQL("select * from medicos where nome='"+ nome+"'");
        try {
            Connection.rs.first();
            form.getjTextFieldCod().setText(String.valueOf(Connection.rs.getInt("id_medico")));
            jTextFieldNomePsq.setText(Connection.rs.getString("nome"));
            jButtonCadMedicoCancelar.setEnabled(true);
            jButtonCadMedicoExcluir.setEnabled(true);
            jButtonjButtonCadMedicoEditar.setEnabled(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(PesqMedico.class.getName()).log(Level.SEVERE, null, ex);
                       
        }
        
        Connection.desconecta();
        
    }//GEN-LAST:event_jTablePsqMedicoMouseClicked

    private void preecherTabela(String SQL){
    ArrayList dados = new ArrayList();
    String [] Colunas = new String[]{"ID","Nome","CRMV","Especialidade",};
    Connection.executaSQL(SQL);
         try {
             Connection.rs.first();
             do{
                 dados.add(new Object[]{Connection.rs.getInt("id_medico"),Connection.rs.getString("nome"),Connection.rs.getInt("crm"),Connection.rs.getString("especialidade") });
                }while(Connection.rs.next());
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, " Erro ao Preencher a Tabela! " + ex);
         }
         
   ModeloTabela modelo = new ModeloTabela(dados, Colunas);
   jTablePsqMedico.setModel (modelo);
   jTablePsqMedico.getColumnModel().getColumn(0).setPreferredWidth(50);
   jTablePsqMedico.getColumnModel().getColumn(0).setResizable(false);
   jTablePsqMedico.getColumnModel().getColumn(1).setPreferredWidth(250);
   jTablePsqMedico.getColumnModel().getColumn(1).setResizable(false);
   jTablePsqMedico.getColumnModel().getColumn(2).setPreferredWidth(80);
   jTablePsqMedico.getColumnModel().getColumn(2).setResizable(false);
   jTablePsqMedico.getColumnModel().getColumn(3).setPreferredWidth(150);
   jTablePsqMedico.getColumnModel().getColumn(3).setResizable(false);
   jTablePsqMedico.getTableHeader().setReorderingAllowed(false);
   jTablePsqMedico.setAutoResizeMode(jTablePsqMedico.AUTO_RESIZE_OFF);
   jTablePsqMedico.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesqMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesqMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesqMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesqMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesqMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadMedicoCancelar;
    private javax.swing.JButton jButtonCadMedicoExcluir;
    private javax.swing.JButton jButtonCadMedicoNovo;
    private javax.swing.JButton jButtonCadMedicoPesquisar;
    private javax.swing.JButton jButtonjButtonCadMedicoEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPsqNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePsqMedico;
    private javax.swing.JTextField jTextFieldNomePsq;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jTextFieldNomePsq
     */
    public javax.swing.JTextField getjTextFieldNomePsq() {
        return jTextFieldNomePsq;
    }

    /**
     * @param jTextFieldNomePsq the jTextFieldNomePsq to set
     */
    public void setjTextFieldNomePsq(javax.swing.JTextField jTextFieldNomePsq) {
        this.jTextFieldNomePsq = jTextFieldNomePsq;
    }

    /**
     * @return the jTextFieldPsqCrm
     */
    

    /**
     * @return the jTextFieldcod
     */
    
}
